server {
    listen 80;
    server_name iam.hqnb.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name iam.hqnb.local;

    ssl_certificate /home/tmduc/Cmeet-Online-Setup-Offline/certs/cert.crt;
    ssl_certificate_key /home/tmduc/Cmeet-Online-Setup-Offline/certs/cert.key;

    # Hỗ trợ upload script hoặc theme lớn
    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:8081; # Keycloak HTTP Port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
