server {
    listen 80;
    server_name iam-hqnb.cmcati.vn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name iam-hqnb.cmcati.vn;

    ssl_certificate /etc/letsencrypt/live/iam-hqnb.cmcati.vn/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/iam-hqnb.cmcati.vn/privkey.pem; # managed by Certbot

    # Hỗ trợ upload script hoặc theme lớn
    client_max_body_size 50M;

    location / {
        proxy_pass http://10.1.6.52:8081; # Keycloak HTTP Port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}